packageExtensions:
  "@strapi/strapi@*":
    dependencies:
      "@swc/core": "1.7.36"
  "@vitejs/plugin-react-swc@*":
    dependencies:
      "@swc/core": "1.7.36"

nodeLinker: node-modules

supportedArchitectures:
  os: ["linux", "darwin"]
  cpu: ["x64", "arm64"]