//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  articles: Articles;
  articlesConnection: ArticlesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArticlesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArticlesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArticlesFilter>;
};

export type DocumentFilter = {
  articles?: InputMaybe<ArticlesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Articles | Folder;

export type ArticlesCover = {
  __typename?: 'ArticlesCover';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type ArticlesCategory = {
  __typename?: 'ArticlesCategory';
  name?: Maybe<Scalars['String']['output']>;
  slug?: Maybe<Scalars['String']['output']>;
};

export type ArticlesAuthorAvatar = {
  __typename?: 'ArticlesAuthorAvatar';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  width?: Maybe<Scalars['Float']['output']>;
  height?: Maybe<Scalars['Float']['output']>;
};

export type ArticlesAuthor = {
  __typename?: 'ArticlesAuthor';
  name?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  avatar?: Maybe<ArticlesAuthorAvatar>;
};

export type Articles = Node & Document & {
  __typename?: 'Articles';
  sourceId: Scalars['Float']['output'];
  translationKey: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  createdAt: Scalars['String']['output'];
  updatedAt: Scalars['String']['output'];
  publishedAt: Scalars['String']['output'];
  sourceUrl?: Maybe<Scalars['String']['output']>;
  cover?: Maybe<ArticlesCover>;
  category?: Maybe<ArticlesCategory>;
  author?: Maybe<ArticlesAuthor>;
  relatedSlugs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  fallbackLocale?: Maybe<Scalars['String']['output']>;
  bodySource?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ArticlesCoverFilter = {
  src?: InputMaybe<StringFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type ArticlesCategoryFilter = {
  name?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
};

export type ArticlesAuthorAvatarFilter = {
  src?: InputMaybe<StringFilter>;
  alt?: InputMaybe<StringFilter>;
  width?: InputMaybe<NumberFilter>;
  height?: InputMaybe<NumberFilter>;
};

export type ArticlesAuthorFilter = {
  name?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  avatar?: InputMaybe<ArticlesAuthorAvatarFilter>;
};

export type ArticlesFilter = {
  sourceId?: InputMaybe<NumberFilter>;
  translationKey?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  createdAt?: InputMaybe<DatetimeFilter>;
  updatedAt?: InputMaybe<DatetimeFilter>;
  publishedAt?: InputMaybe<DatetimeFilter>;
  sourceUrl?: InputMaybe<StringFilter>;
  cover?: InputMaybe<ArticlesCoverFilter>;
  category?: InputMaybe<ArticlesCategoryFilter>;
  author?: InputMaybe<ArticlesAuthorFilter>;
  relatedSlugs?: InputMaybe<StringFilter>;
  fallbackLocale?: InputMaybe<StringFilter>;
  bodySource?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type ArticlesConnectionEdges = {
  __typename?: 'ArticlesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Articles>;
};

export type ArticlesConnection = Connection & {
  __typename?: 'ArticlesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ArticlesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateArticles: Articles;
  createArticles: Articles;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateArticlesArgs = {
  relativePath: Scalars['String']['input'];
  params: ArticlesMutation;
};


export type MutationCreateArticlesArgs = {
  relativePath: Scalars['String']['input'];
  params: ArticlesMutation;
};

export type DocumentUpdateMutation = {
  articles?: InputMaybe<ArticlesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  articles?: InputMaybe<ArticlesMutation>;
};

export type ArticlesCoverMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type ArticlesCategoryMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
};

export type ArticlesAuthorAvatarMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  width?: InputMaybe<Scalars['Float']['input']>;
  height?: InputMaybe<Scalars['Float']['input']>;
};

export type ArticlesAuthorMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  avatar?: InputMaybe<ArticlesAuthorAvatarMutation>;
};

export type ArticlesMutation = {
  sourceId?: InputMaybe<Scalars['Float']['input']>;
  translationKey?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  createdAt?: InputMaybe<Scalars['String']['input']>;
  updatedAt?: InputMaybe<Scalars['String']['input']>;
  publishedAt?: InputMaybe<Scalars['String']['input']>;
  sourceUrl?: InputMaybe<Scalars['String']['input']>;
  cover?: InputMaybe<ArticlesCoverMutation>;
  category?: InputMaybe<ArticlesCategoryMutation>;
  author?: InputMaybe<ArticlesAuthorMutation>;
  relatedSlugs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  fallbackLocale?: InputMaybe<Scalars['String']['input']>;
  bodySource?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type ArticlesPartsFragment = { __typename: 'Articles', sourceId: number, translationKey: string, locale: string, slug: string, title: string, description: string, createdAt: string, updatedAt: string, publishedAt: string, sourceUrl?: string | null, relatedSlugs?: Array<string | null> | null, fallbackLocale?: string | null, bodySource?: string | null, body?: string | null, cover?: { __typename: 'ArticlesCover', src?: string | null, alt?: string | null } | null, category?: { __typename: 'ArticlesCategory', name?: string | null, slug?: string | null } | null, author?: { __typename: 'ArticlesAuthor', name?: string | null, email?: string | null, avatar?: { __typename: 'ArticlesAuthorAvatar', src?: string | null, alt?: string | null, width?: number | null, height?: number | null } | null } | null };

export type ArticlesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ArticlesQuery = { __typename?: 'Query', articles: { __typename: 'Articles', id: string, sourceId: number, translationKey: string, locale: string, slug: string, title: string, description: string, createdAt: string, updatedAt: string, publishedAt: string, sourceUrl?: string | null, relatedSlugs?: Array<string | null> | null, fallbackLocale?: string | null, bodySource?: string | null, body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cover?: { __typename: 'ArticlesCover', src?: string | null, alt?: string | null } | null, category?: { __typename: 'ArticlesCategory', name?: string | null, slug?: string | null } | null, author?: { __typename: 'ArticlesAuthor', name?: string | null, email?: string | null, avatar?: { __typename: 'ArticlesAuthorAvatar', src?: string | null, alt?: string | null, width?: number | null, height?: number | null } | null } | null } };

export type ArticlesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArticlesFilter>;
}>;


export type ArticlesConnectionQuery = { __typename?: 'Query', articlesConnection: { __typename?: 'ArticlesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ArticlesConnectionEdges', cursor: string, node?: { __typename: 'Articles', id: string, sourceId: number, translationKey: string, locale: string, slug: string, title: string, description: string, createdAt: string, updatedAt: string, publishedAt: string, sourceUrl?: string | null, relatedSlugs?: Array<string | null> | null, fallbackLocale?: string | null, bodySource?: string | null, body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cover?: { __typename: 'ArticlesCover', src?: string | null, alt?: string | null } | null, category?: { __typename: 'ArticlesCategory', name?: string | null, slug?: string | null } | null, author?: { __typename: 'ArticlesAuthor', name?: string | null, email?: string | null, avatar?: { __typename: 'ArticlesAuthorAvatar', src?: string | null, alt?: string | null, width?: number | null, height?: number | null } | null } | null } | null } | null> | null } };

export const ArticlesPartsFragmentDoc = gql`
    fragment ArticlesParts on Articles {
  __typename
  sourceId
  translationKey
  locale
  slug
  title
  description
  createdAt
  updatedAt
  publishedAt
  sourceUrl
  cover {
    __typename
    src
    alt
  }
  category {
    __typename
    name
    slug
  }
  author {
    __typename
    name
    email
    avatar {
      __typename
      src
      alt
      width
      height
    }
  }
  relatedSlugs
  fallbackLocale
  bodySource
  body
}
    `;
export const ArticlesDocument = gql`
    query articles($relativePath: String!) {
  articles(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArticlesParts
  }
}
    ${ArticlesPartsFragmentDoc}`;
export const ArticlesConnectionDocument = gql`
    query articlesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ArticlesFilter) {
  articlesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArticlesParts
      }
    }
  }
}
    ${ArticlesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      articles(variables: ArticlesQueryVariables, options?: C): Promise<{data: ArticlesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticlesQueryVariables, query: string}> {
        return requester<{data: ArticlesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticlesQueryVariables, query: string}, ArticlesQueryVariables>(ArticlesDocument, variables, options);
      },
    articlesConnection(variables?: ArticlesConnectionQueryVariables, options?: C): Promise<{data: ArticlesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticlesConnectionQueryVariables, query: string}> {
        return requester<{data: ArticlesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticlesConnectionQueryVariables, query: string}, ArticlesConnectionQueryVariables>(ArticlesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "/api/tina/gql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  